
templates:

  freespace:
    free_space:
      path: /home/down/down
      space: 10240

  de:
    deluge:
      path: /home/down/down/
      host: localhost
      port: 58846
      username: pppppp
      password: Pp123456

  qb:
    qbittorrent:
      path: /home/down/down/
      host: localhost
      port: 2017
      username: pppppp
      password: Pp123456

  size:
    content_size:
      min: 600
      max: 666666
      strict: no


tasks:
  chd:
    rss: https://chdbits.co/torrentrss.php?rows=10&tea3=1&tea14=1&tea13=1&tea1=1&tea2=1&tea15=1&tea12=1&tea11=1&tea10=1&tea8=1&tea16=1&linktype=dl&passkey=23105215e54f55b7fa7a8c3964aa2800
    seen:
      fields:
        - url
    accept_all: yes
    template: de
    deluge:
      max_up_speed: 100000

  sky:
    rss: https://hdsky.me/torrentrss.php?rows=10&tea6=1&tea1=1&tea28=1&tea9=1&tea31=1&tea18=1&tea22=1&tea34=1&tea24=1&tea26=1&tea30=1&tea25=1&tea33=1&tea35=1&tea36=1&linktype=dl&passkey=43d146b810b9784aeb767b2826d11410
    seen:
      fields:
        - url
    accept_all: yes
    template: de

  spring:
    rss: https://springsunday.net/torrentrss.php?rows=10&rescue=1&linktype=dl&passkey=f46c1a543f7f3db53e018d2d9b1f69ae
    seen:
      fields:
        - url
    accept_all: yes
    template: de
    deluge:
      max_up_speed: 10000

  spring1:
    rss: 
      url: https://springsunday.net/torrentrss.php?rows=10&linktype=dl&passkey=f46c1a543f7f3db53e018d2d9b1f69ae
      other_fields: [link]
    nexusphp:
      cookie: 'SPRINGID=d0sg296hlfc851jbqkrgs7j627onh6rpnmsus6is8qeu6v2n513p36dbjrjmtpf7; __utmt=1; __utma=37122914.303624818.1625104882.1625104882.1625104882.1; __utmb=37122914.2.10.1625104882; __utmc=37122914; __utmz=37122914.1625104882.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
'
      discount: 
      - 2xfree 
      - free
    template: de
    deluge:
      max_up_speed: 10000

  ob:
    rss: https://ourbits.club/torrentrss.php?rows=10&tea1=1&tea2=1&tea12=1&tea42=1&tea46=1&tea47=1&tea48=1&tea3=1&tea18=1&tea31=1&tea41=1&passkey=0e232a75db515e675ccd82c1272304f2&https=1&linktype=dl
    seen:
      fields:
        - url
    accept_all: yes
    template: de
    deluge:
      max_up_speed: 50000

  ttg:
    rss: 
      url: https://totheglory.im/putrssde.php?par=dnZ2NTEsNTIsNTMsNTQsMTA4LDEwOSw2Miw2Myw2Nyw2OSw3MCw3Myw3Niw3NCw3NSw4Nyw4OCw5MCw5OSw4Miw4Myw1OSw1Nyw1OCwxMDMsMTAxLDYwLDkxLDg0LDkyfHx8YTFjOWE5M2EyMTA2NzE3MDY2MWEwM2RmNzc5OTJiNjB6eg==
      other_fields: [link]
    nexusphp:
      cookie: 'uid=157353; pass=ddce05c5518025bd89b08b8df793c364; laccess=1624418609; PHPSESSID=j5j6vhfi6ddnas7i8h75c7fah6'
      discount: 
      - 2xfree 
      - free
      hr: no
    template: qb

  u2:
    rss: 
      url: https://u2.dmhy.org/torrentrss.php?rows=10&trackerssl=1&passkey=b9175d9f0c4601e4e7eff450803ba5c8&linktype=dl
      other_fields: [link]
    nexusphp:
      cookie: 'nexusphp_u2=b4b611b777d0bd6c3b1e40d7341d6834f0ae46aeb60718122ef13bce7c66e94c06fcf9926e558a72120917ec4b324795'
      discount: 
      - 2xfree 
      - free
    template: de
    deluge:
      max_up_speed: 50000

  hdh:
    rss: 
      url: https://hdhome.org/torrentrss.php?rows=10&exp=180&linktype=dl&passkey=1145b652x1625895765x118703x180xb22b186e2096542b6d55e21d838bd471
      other_fields: [link]
    nexusphp:
      cookie: 'cf_clearance=34fcd200789ca809430e98c74bc715bfd1273710-1622638942-0-150; c_secure_uid=MTE4NzAz; c_secure_pass=4c1f0f0b683d97bd8458d0d79e30fcbf; c_secure_ssl=eWVhaA%3D%3D; c_secure_tracker_ssl=eWVhaA%3D%3D; c_secure_login=bm9wZQ%3D%3D; c_secure_uid=MTE4NzAz; c_secure_pass=4c1f0f0b683d97bd8458d0d79e30fcbf; c_secure_ssl=eWVhaA%3D%3D; c_secure_tracker_ssl=eWVhaA%3D%3D; c_secure_login=bm9wZQ%3D%3D'
      discount: 
      - 2xfree 
      - free
    template: de
    deluge:
      max_up_speed: 25000


web_server:
  port: 6566
  web_ui: yes

schedules: no



