
templates:

  freespace:
    free_space:
      path: /home/down/down
      space: 10240

  de:
    deluge:
      path: /home/down/down/
      host: localhost
      port: 58846
      username: pppppp
      password: Pp123456

  qb:
    qbittorrent:
      path: /home/down/down/
      host: localhost
      port: 2017
      username: pppppp
      password: Pp123456

  size:
    content_size:
      min: 600
      max: 666666
      strict: no


tasks:
#这玩意儿还用教？


web_server:
  port: 6566
  web_ui: yes

schedules: no



