
templates:

  de:
    deluge:
      path: /home/dddd/torrents/qbittorrent/
      host: localhost
      port: 58846
      username: dddd
      password: dddd1234

  qb:
    qbittorrent:
      path: /home/dddd/torrents/qbittorrent/
      host: localhost
      port: 2017
      username: dddd
      password: dddd1234




tasks:

      

schedules: no



